import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../../styles/globals.css';
import { NavigationBar } from '@/components/navigationBar';
import Footer from '@/components/footer';
import { Providers } from '@/app/(user)/providers';
import { ErrorBoundary } from 'next/dist/client/components/error-boundary';
import { Suspense } from 'react';
import Loading from '@/app/(user)/loading';
import Error from '@/app/(user)/error';
import SessionWrapper from '@/app/SessionProvider';
import StoreProvider from '@/app/StoreProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <SessionWrapper>
        <body>
          <StoreProvider>
            <Providers
              themeProps={{ attribute: 'class', defaultTheme: 'dark' }}
            >
              <NavigationBar />
              <main className="container mx-auto min-h-screen max-w-7xl px-6 pt-16">
                <ErrorBoundary errorComponent={Error}>
                  <Suspense fallback={<Loading />}>{children}</Suspense>
                </ErrorBoundary>
              </main>
              <Footer />
            </Providers>
          </StoreProvider>
        </body>
      </SessionWrapper>
    </html>
  );
}
